copyright = "© matteo muscella"
defaultContentLanguage = "en"
enableRobotsTXT = true
languageCode = "en"
timeZone = "Europe/Rome"
timeout = "120s"
title = "mattmusc photos"

[params]
  defaultTheme = "dark"
  description = "My photography showcase"
  title = "mattmusc photos"
  [params.author]
    email = "matteo[dot]muscella[at]yahoo[dot]com"
    name = "Matteo Muscella"
  [params.socialIcons]
    facebook = "https://www.facebook.com/MattMusc"
    instagram = "https://www.instagram.com/mattmusc"
    github = "https://github.com/mattmusc"
    #youtube = "https://www.youtube.com/"
    #email = "mailto:user@example.com"
    website = "https://www.mattmusc.com"
    #mastodon = "https://example.com"
    #pixelfed = "https://example.com"
    #mixcloud = "https://mixcloud.com"
  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 95
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[menu]
  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/mattmusc/mattmusc-hugo-portfolio/"
    weight = 3

[services]
  [services.rss]
    limit = 100
